# Uncomment this line to define a global platform for your project
platform :ios, '8.1'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Github' do

  #pod 'Neeman', :git => 'https://github.com/intellum/neeman.git'
  podLocal = ENV['POD_LOCAL_HOME']
  pod 'Neeman', :path => podLocal + '/Neeman'

end

